### ISSUE TITLE
Can I use your joi.d.ts to replace the current @types/joi/index.d.ts file in my local repository to test it

### ISSUE THREAD

**Issue by Yuncoong** [hjkcai/typesafe-joi#1]
Hi Jingkun,

I'm really excited to see your project on the typesafe-joi. As mentioned in the title can I replace my @types/joi/index.d.ts file with your joi.d.ts to do a quick test? And also is there a reason you only support joi.validate and joi.attemp not joi.assert? Thanks!

**Comment by hjkcai** [comment]
Hi. Sorry but I do not really understand your question. This project is licensed under MIT. You are free to do whatever you want. 

`Joi.assert` is supported. See [joi.d.ts:1398](https://github.com/hjkcai/typesafe-joi/blob/master/joi.d.ts#L1398). But joi produces only errors. So I think the current type definition of `Joi.assert` is correct.

**Comment by hjkcai** [comment]
I will close this issue since it has been inactive for a long time
