### ISSUE TITLE
Treatment of concat()

### ISSUE THREAD

**Issue by brabeji** [hjkcai/typesafe-joi#10]
Hello again @hjkcai 😁 

I've tried to use `.concat()` of object schemas and i got union of them which seems like a bug so I've changed:
```
concat<T extends AbstractSchema> (schema: T): SchemaType<Schema, Value | SchemaValue<T>>
```
to
```
concat<T extends AbstractSchema> (schema: T): SchemaType<Schema, Value & SchemaValue<T>>
```

and now I correctly get extended schema. Do you see any problem with this?

Thanks for the lib!

**Comment by hjkcai** [comment]
Sorry but it is not that simple 😞. I have tested the behavior and read the source code of `concat()`. It is REALLY complicated. I will try to implement it (but not soon).

BTW I am working (slowly) on typesafe-joi 2.0. It will be more stable and closer to the runtime behavior of joi. The `default` function is (maybe) perfectly implemented. Check it out on the branch [new-implementation](https://github.com/hjkcai/typesafe-joi/tree/new-implementation)

**Comment by brabeji** [comment]
Yeah, I didn't bother and assumed concat just for object types, which might be a big issue 😅 

That's awesome to hear about the 2.0, you rock!

Thanks again

**Comment by hjkcai** [comment]
Hi @brabeji

Could you please show me an example usage of `concat` that results in `A & B` instead of `A | B`? I read the source code of joi and I don't think `A & B` is correct. It works like `A | B` both on any types

**Comment by brabeji** [comment]
Hello @hjkcai 

I have two "form fragments" with their own respective schemas:

```
const formSchema = Joi.object({})
	.default({})
	.concat(CompanyBillingInfoFormFragmentSchema) // object schema
	.concat(CompanyPaymentFormFragmentSchema);  // object schema
```

I think the type of valid value for this schema isn't union (either A or B) of these.

**Comment by hjkcai** [comment]
In this case `concat` is `A & B` because it merges objects. That is right. 

However you should use `keys` instead of `concat`. Because you may get errors when the two fragments has one or more duplicate keys.

**Comment by brabeji** [comment]
Well, I can't use keys as they work with plain objects and not schemas. Here I need to have my partial schemas as true schema instances for them to work standalone.

```
const formSchema = Joi.object({})
	.default({})
	.keys(CompanyBillingInfoFormFragmentSchema);  // error, CompanyBillingInfoFormFragmentSchema is already a schema instance, not a map of keys.
```

**Comment by brabeji** [comment]
Maybe the behavior should be doing `&` on conflicting keys types, same as typescript does:
```
interface A {
	foo: string;
}

interface B {
	foo: number;
}

type C = A & B;
C['foo']; // string & number
```

**Comment by hjkcai** [comment]
On duplicate key, the `concat` concats these two schema. The `concat` does not work on different types. Your example results in an error

**Comment by hjkcai** [comment]
It is time to try 2.0.0😀 The behavior of concat is very close to the vanilla joi now
