### ISSUE TITLE
Required type inferred as optional

### ISSUE THREAD

**Issue by bard** [hjkcai/typesafe-joi#13]
Using the example from the README:

```js
const x = joi.attempt(
  {},
  joi.array().items({
    id: joi.number().integer().required(),
    email: joi.string().email()
  }).required()
)
```

Type of `x` is `{ id?: number, email?: string }` instead of `{ id: number, email?: string }` (i.e. `id` is inferred as optional).

- typesafe-joi 2.0.1
- typescript 3.4.5
- @hapi/joi 15.0.3

**Comment by hjkcai** [comment]
Sorry I am still working on the tests. I will fix it soon

**Comment by hjkcai** [comment]
Hey @bard, sorry for the late. I cannot reproduce this issue. I got `x` as type of:

```typescript
const x: ({
    id: number;
} & {
    email?: string | undefined;
})[]
```

which is exactly `{ id: number, email?: string }[]`. Do you still have this problem? If so, please paste the type of `schema`

```typescript
const schema = joi.array().items({
  id: joi.number().integer().required(),
  email: joi.string().email()
}).required()
```

What I've got is:

```typescript
const schema: joi.ArraySchema<joi.Value<any[], ({
    id: number;
} & {
    email?: string | undefined;
})[] & joi.Schema.InternalArrayType<false>, never, undefined, joi.Value.Presence.Required>>
```

**Comment by bard** [comment]
Tested using typescript 3.4.5 and typesafe-joi 2.0.2, inferred schema looks ok, same as you. I think we can close this, thanks!

**Comment by sljuka** [comment]
Hey, I'm also having this issue. Running:
```js
const validatedParams = joi.attempt(
    {},
    joi
        .array()
        .items({
            id: joi
                .number()
                .integer()
                .required(),
            email: joi.string().email(),
        })
        .required()
);
```

and getting:
```js
const validatedParams: ({} & {
    id?: number;
    email?: string;
})[]
```
from package.lock:
typescript: 3.4.5
typesafe-joi: 2.0.2 (also tried 2.0.6)
@hapi/joi: 15.0.3

After removing and reinstalling all deps the behavior is still the same. 🤔 
Nice package 💯 
Would love to give you a hand with this, but after checking the source I feel like my TS skills are not up for the task.

**Comment by hjkcai** [comment]
@sljuka Try upgrade typesafe-joi to 2.0.6

![image](https://user-images.githubusercontent.com/731326/59689163-ba58ec80-9211-11e9-9ce7-f187324d3838.png)

**Comment by sljuka** [comment]
@hjkcai thank you for quick response. Turns out `strict` mode in tsconfig was turned off. After switching it on all was good.
