### ISSUE TITLE
Explain conditions where joi schema is undefined

### ISSUE THREAD

**Issue by bbangert** [hjkcai/typesafe-joi#16]
I'm curious why the example shown and in my own code using `attempt` results in the type inferred being the schema or `undefined`. Since `attempt` throws the validation error, why would the resulting object possibly be `undefined`?

This occurs when using `joi.object`, even if I require a set of keys. Here's an example schema:
```typescript
const BASE_MESSAGE_SCHEMA = Joi.object()
  .keys({
    event: Joi.string().required(),
    uid: Joi.string().required()
  })
  .unknown(true);
```
The object must have 2 keys along with extras. What is the error condition that requires checking for `undefined`?

**Comment by hjkcai** [comment]
Because this is how joi works.

```typescript
Joi.attempt(undefined, Joi.object())    // undefined
Joi.attempt(undefined, Joi.object().keys({ foo: 'bar' })))    // undefined
Joi.attempt({}, Joi.object().keys({ foo: 'bar' })))    // error - the key `foo` does not exist
Joi.attempt(undefined, Joi.object().keys({ foo: 'bar' }).required())    // error - the value itself is required
```

So if you don't want the `undefined` type to show in the result, append `.required()` to the top of the schema.

```typescript
const BASE_MESSAGE_SCHEMA = Joi.object()
  .keys({
    event: Joi.string().required(),
    uid: Joi.string().required()
  })
  .unknown(true)
  .required();
```

**Comment by bbangert** [comment]
Thank you! For some reason this was not at all obvious to me reading the Joi docs.

**Comment by hjkcai** [comment]
You are welcomed. In fact joi docs did not say it can validate against `undefined` by default🤣

BTW could you please give typesafe-joi a star, if you like it😄
