### ISSUE TITLE
problems with forbiddenKeys

### ISSUE THREAD

**Issue by thomasmikava** [hjkcai/typesafe-joi#17]
I'm very excited that optionalKeys are added. I've tested today with 2.0.2 version.
As the documentation states, forbiddenKeys are added too. However, I think there is a bug.

Take this schema for example,
```ts
const userSchema = Joi.object({
	name: Joi.string().required(),
	surname: Joi.string().required(),
	age: Joi.number()
}).forbiddenKeys("name", "surname");
```

the type of this schema results in
```ts
ObjectSchema<Value<never, never, never, never, never>>
```

thus the resulting type is never, instead of { age?: number | undefined };

If I dont's pass anything to forbiddenKeys, it's still "never";

**Comment by hjkcai** [comment]
Fixed in 2.0.3

**Comment by thomasmikava** [comment]
@hjkcai, The bug is fixed, thanks. However, all values at such keys are marked as never, so I can't use it for creating another object.

For instance, when writing
```ts
const userSchema = Joi.object({
	name: Joi.string().required(),
	surname: Joi.string().required(),
	age: Joi.number()
}).forbiddenKeys("name", "surname").required();

type IUser = Joi.Literal<typeof userSchema>;

const user: IUser = {
	age: 5,
};
```

I get the following error:
```ts
Type '{ age: number; }' is not assignable to type '{ name: never; surname: never; } & { age?: number | undefined; }'.
  Type '{ age: number; }' is missing the following properties from type '{ name: never; surname: never; }': name, surname
```

Currently I handle this problem by creating custom generic type ExcludeNeverKeys, which helps me to totally remove keys that extend never.

**Comment by hjkcai** [comment]
Sorry for that. These keys should be optional in the resulting object. I will publish a new version to solve this.

**Comment by hjkcai** [comment]
@thomasmikava Try 2.0.4 please. The new version will remove all forbidden keys completely. In your case, the resulting type will be `{ age?: number }` now.

**Comment by thomasmikava** [comment]
Thanks, it has been fixed
