### ISSUE TITLE
Problems with Joi.alternatives

### ISSUE THREAD

**Issue by thomasmikava** [hjkcai/typesafe-joi#18]
The following code worked in early versions: 

```ts
const bSchema = Joi.object({
	name: Joi.string().required(),
	age: Joi.number().required(),
});

const aSchema = Joi.object({
	surname: Joi.string().required(),
	age: Joi.number().required(),
});

const Schema = Joi.alternatives(aSchema, bSchema);
```
Schema used to have correct types.

However, in current version, if we convert Schema to type, we get: 
```ts
{ age: number; } & {}
```
name and surname are completely lost.
So it probably behaves more like & than |

**Comment by hjkcai** [comment]
Thanks! This was a mistake. Fixed in 2.0.5
