### ISSUE TITLE
Inference bug with typesafe-joi 3.0.5 / TypeScript 3.5

### ISSUE THREAD

**Issue by bard** [hjkcai/typesafe-joi#19]
```js
import Joi from 'typesafe-joi'

const schema = Joi.object().keys({
  receiveUpdates: Joi.boolean().required()
})

const value = Joi.attempt({}, schema)

/* type of value:

const value: ({} & {
    [x: string]: string | number | boolean | ({
        [x: string]: string | number | boolean | (... & {
            [x: string]: string | number | boolean | (... & ...) | null | undefined;
        }) | null | undefined;
    } & {
        [x: string]: string | ... 4 more ... | undefined;
    }) | null | undefined;
}) | undefined

*/

type T = Joi.Literal<typeof schema>

/* type of T: any */
```

**Comment by hjkcai** [comment]
Thanks @brad

However it seems fine. I cannot reproduce this issue. Could you please try to reinstall everything?

<img width="1082" alt="Screen Shot 2019-06-08 at 2 42 11 PM" src="https://user-images.githubusercontent.com/731326/59143269-d41d5700-89fb-11e9-82bb-d2cf119fe99d.png">

**Comment by bard** [comment]
Well, beats me, I did everything in a minimal repro to be certain and now I cannot reproduce it either. Apologies for the noise and thanks for your patience.
