### ISSUE TITLE
Support Object Pattern

### ISSUE THREAD

**Issue by thomasmikava** [hjkcai/typesafe-joi#2]
Hello. I have a little problem of using `Joi.object().pattern()`

I have the following schema:
```ts
const schema = Joi.object().keys({
	somKey: Joi.number().integer().required(),
	changedInfo: Joi.object().pattern(/[\da-z-]+/, Joi.object().keys({
		id: Joi.number().integer().optional(),
		title: Joi.string().allow(null).optional(),
	})).required()
});
```
typesafe-joi does not recognize that changedInfo can have some keys and those keys will have the shape of `{id?: number, title?: string | null}`

I will try to figure out myself and if I find a solution, definitely will comment here. Meanwhile, if you give me some hint, I will appreciate!

**Comment by thomasmikava** [comment]
What if instead of
```ts
  pattern (pattern: SchemaLike, schema: SchemaLike): this
```
we write
```ts
  pattern<T extends SchemaLike, K extends SchemaLike> (pattern: T, schema: K): SchemaType<Schema, {[key: string]: SchemaValue<K>}>
  pattern<K extends SchemaLike> (pattern: RegExp, schema: K): SchemaType<Schema, {[key: string]: SchemaValue<K>}>
```
?

I think my case is solved with this change. However, it needs more testing.

**Comment by hjkcai** [comment]
I do not think this solves the problem. I tried to change the signature of `pattern` to:

```typescript
pattern<T extends SchemaLike> (pattern: RegExp | SchemaLike, schema: T): SchemaType<Schema, MergeObject<Value, Record<string, SchemaValue<T>>>>
```

However, calling `pattern` multiple times is fine in vanilla joi. In the following case, TypeScript cannot describe the shape of the object at all:

```typescript
const Schema = Joi.object({ A: Joi.boolean() })
  .pattern(/[0-9]/, Joi.number())
  .pattern(/[a-z]/, Joi.string())

// results in
type Result = { A?: boolean } & { [key: string]: number | undefined } & { [key: string]: string | undefined }

type A = Result['A']    // boolean | undefined
type B = Result['b']    // undefined, because (number | undefined) & (string | undefined) => undefined
```

I think it is better to let users define the type by themselves?

**Comment by thomasmikava** [comment]
Oh, I didn't know that we can call pattern twice.

I suggest you to update the type definitions as you wrote and add in limitations section that in case of calling `pattern` several times, types will be different.

We can consider this issue closed. Thank you!

**Comment by hjkcai** [comment]
A new version is published for several updates including this one. Please have a try :>
