### ISSUE TITLE
Problem with Joi.alternatives

### ISSUE THREAD

**Issue by thomasmikava** [hjkcai/typesafe-joi#20]
Consider the following schema:
```ts
const schema = Joi.alternatives([
	Joi.number(),
	Joi.array().items(Joi.number()),
]);
```
This produces a correct type `number | number[]`

However, if I add allow(null),
```ts
const schema = Joi.alternatives([
	Joi.number(),
	Joi.array().items(Joi.number()),
]).allow(null);
```

then the produced type is only `number[]`, while it has to be `number | number[] | null`

**Comment by hjkcai** [comment]
Fixed in 2.0.6
