### ISSUE TITLE
Is it possible to extract types without calling validate?

### ISSUE THREAD

**Issue by karthikiyengar** [hjkcai/typesafe-joi#3]
Thanks for the great library, this is extremely useful :-)

Is it possible to extract the types from a schema without calling `attempt` or `validate` similar to https://github.com/TCMiranda/joi-extract-type ?

Since I use Joi to validate requests to my API server, I would like to improve typings for the `req.body`/`req.query` by extracting types from the validation schema. Something like what follows. 

```
interface IValidatedRequest<T> extends Request {
  body: Joi.extractTypes<T>
}
```
Any suggestions?

**Comment by hjkcai** [comment]
Of course. See definition of `SchemaValue<T>`, in which `T` is `SchemaLike`. It is similar to `extractTypes`.

```typescript
const schema = Joi.object({ a: Joi.number() })
type value = Joi.SchemaValue<typeof schema>
```

BTW I am also doing API validation by using typesafe-joi. It is incredibly useful 😃

**Comment by karthikiyengar** [comment]
Thanks a lot, this works perfectly!
